import {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowDownRight,
  ArrowDownToLine,
  ArrowLeft,
  ArrowUp,
  ArrowUpRight,
  BadgePlus,
  Banknote,
  Bean,
  Bell,
  Bitcoin,
  BrushCleaning,
  Bug,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleEllipsis,
  CirclePlus,
  ClipboardPaste,
  Clock,
  Cloud,
  Coins,
  Compass,
  Copy,
  createLucideIcon,
  Delete,
  Download,
  Ellipsis,
  EllipsisVertical,
  Euro,
  Eye,
  EyeOff,
  FileText,
  Filter,
  FlaskConical,
  FolderPlus,
  Gauge,
  Glasses,
  HandCoins,
  HeartHandshake,
  ImagePlus,
  Images,
  ImageUp,
  Info,
  Keyboard,
  KeyRound,
  Landmark,
  Languages,
  Lock,
  LockOpen,
  LogOut,
  Maximize,
  Minimize,
  MessageCircle,
  MessageCircleMore,
  Minus,
  Monitor,
  Moon,
  Palette,
  Pause,
  Pencil,
  PencilLine,
  PhoneOff,
  Pipette,
  Play,
  Plus,
  QrCode,
  Radio,
  RadioTower,
  RefreshCcw,
  Repeat,
  Reply,
  RotateCw,
  Save,
  ScanLine,
  Scissors,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Shirt,
  Smartphone,
  Smile,
  SquarePlus,
  Sun,
  SwitchCamera,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  UserPlus,
  UserRound,
  Users,
  VenetianMask,
  Wallet,
  X,
  Zap,
} from "lucide-react-native";

const Request = createLucideIcon("Request", [
  [
    "path",
    {
      d: "M12 3v11.8c0 1.7-.7 3.3-1.9 4.5L7 22.4 2.6 18l4.2-4.2L9.9 3.7A1.1 1.1 0 0 1 12 4Z",
      key: "left",
    },
  ],
  [
    "path",
    {
      d: "M12 3v11.8c0 1.7.7 3.3 1.9 4.5l3.1 3.1 4.4-4.4-4.2-4.2-3.1-10.1A1.1 1.1 0 0 0 12 4Z",
      key: "right",
    },
  ],
  ["path", { d: "m4.8 15.8 4.4 4.4M19.2 15.8l-4.4 4.4", key: "cuffs" }],
]);

// Lucide's Mail and IdCard crossed out like its PhoneOff; Lucide ships neither.
const MailOff = createLucideIcon("MailOff", [
  ["path", { d: "m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7", key: "flap" }],
  ["rect", { x: "2", y: "4", width: "20", height: "16", rx: "2", key: "body" }],
  ["path", { d: "M22 2 2 22", key: "slash" }],
]);

const IdCardOff = createLucideIcon("IdCardOff", [
  ["path", { d: "M16 10h2M16 14h2", key: "lines" }],
  ["path", { d: "M6.17 15a3 3 0 0 1 5.66 0", key: "shoulders" }],
  ["circle", { cx: "9", cy: "11", r: "2", key: "head" }],
  ["rect", { x: "2", y: "5", width: "20", height: "14", rx: "2", key: "card" }],
  ["path", { d: "M22 2 2 22", key: "slash" }],
]);

export const icons = {
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowDownRight,
  ArrowDownToLine,
  ArrowLeft,
  ArrowUp,
  ArrowUpRight,
  BadgePlus,
  Banknote,
  Bean,
  Bell,
  Bitcoin,
  BrushCleaning,
  Bug,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleEllipsis,
  CirclePlus,
  ClipboardPaste,
  Clock,
  Cloud,
  Coins,
  Compass,
  Copy,
  Delete,
  Download,
  Ellipsis,
  EllipsisVertical,
  Euro,
  Eye,
  EyeOff,
  FileText,
  Filter,
  FlaskConical,
  FolderPlus,
  Gauge,
  Glasses,
  HandCoins,
  HeartHandshake,
  IdCardOff,
  ImagePlus,
  Images,
  ImageUp,
  Info,
  Keyboard,
  KeyRound,
  Landmark,
  Languages,
  Lock,
  LockOpen,
  LogOut,
  MailOff,
  Maximize,
  Minimize,
  MessageCircle,
  MessageCircleMore,
  Minus,
  Monitor,
  Moon,
  Palette,
  Pause,
  Pencil,
  PencilLine,
  PhoneOff,
  Pipette,
  Play,
  Plus,
  QrCode,
  Radio,
  RadioTower,
  RefreshCcw,
  Repeat,
  Reply,
  Request,
  RotateCw,
  Save,
  ScanLine,
  Scissors,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Shirt,
  Smartphone,
  Smile,
  SquarePlus,
  Sun,
  SwitchCamera,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  UserPlus,
  UserRound,
  Users,
  VenetianMask,
  Wallet,
  X,
  Zap,
};

export type IconName = keyof typeof icons;
